[package]
name = "thiccfetch"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
codegen-units = 1
lto = "fat"
debug = false
panic = "abort"
strip = "symbols"

[dependencies]
local-ip-address = "0.6.3"